name: learn-github-actions
on:
  push:
    branches: [ master ]
  # provides an ability to run workflows against pull requests from forks with token that has read and write access
  # in order to add comments on PR (https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request_target)
  pull_request_target:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout pull-request head reference with required security restrictions in case of "pull_request_target" event
      - name: Checkout PR
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          # don't persists credentials in order to reduce security issues related to "pull_request_target" event
          # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request_target
          # https://securitylab.github.com/research/github-actions-preventing-pwn-requests
          persist-credentials: false

      # checkout commit reference not related to pull request in case of "pull_request_target" event absence
      - name: Checkout
        if: github.event_name != 'pull_request_target'
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      # don't cache .m2 directory in order to reduce security issues related to "pull_request_target" event
      # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request_target
      # https://securitylab.github.com/research/github-actions-preventing-pwn-requests
      - name: Cache Maven packages
        if: github.event_name != 'pull_request_target'
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Validate
        run: mvn -B -V clean validate -Dcheckstyle.failOnViolation=true

      - name: Publish checkstyle report
        if: always() # in order to publish report even if previous step is failed
        # use sha commit references in order to reduce security issues related to unverified actions and their creators
        uses: jwgmeligmeyling/checkstyle-github-action@50292990e18466f2c5d95d04ff5fab931254fa5f
        with:
          name: Checkstyle Report
          path: '**/checkstyle-result.xml'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile
        run: mvn -B -V compile -Dcheckstyle.skip=true

      - name: Test
        run: mvn -B -V verify -Dmaven.test.failure.ignore=true -Dcheckstyle.skip=true

      - name: Publish test report
        # use sha commit references in order to reduce security issues related to unverified actions and their creators
        uses: scacap/action-surefire-report@ad808943e6bfbd2e6acba7c53fdb5c89534da533
        with:
          check_name: Test Report
          report_paths: '**/*-reports/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_test_failures: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: greeting-service-artifacts
          path: |
            target/greeting-service-*.jar
            target/greeting-service-*.jar.original
          if-no-files-found: error

      - name: Version extraction
        id: version-extraction
        run: echo "::set-output name=artifact_version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
    outputs:
      # output parameter that is required for further usage in dependent (downstream) jobs
      artifact_version: ${{ steps.version-extraction.outputs.artifact_version }}

  publish-snapshot:
    needs: [ build ]
    # runs only if the event is triggered against secure environment ("master" branch) and
    # produced artifact version is related to SNAPSHOT
    if: >
      github.ref == 'refs/heads/master' && github.event_name == 'push' &&
      endsWith(needs.build.outputs.artifact_version, '-SNAPSHOT')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          server-id: ossrh # value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
          settings-path: ${{ github.workspace }} # store not in a default location to not overwrite by cache restoring

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Version details
        run: echo "Artifact version to publish - ${{ needs.build.outputs.artifact_version }}"

      - name: Package
        run: mvn -B -V -s $GITHUB_WORKSPACE/settings.xml clean package -DskipTests=true -Dcheckstyle.skip=true

  publish-final:
    needs: [ build ]
    # runs only if the event is triggered against secure environment ("master" branch) and
    # produced artifact version is final
    if: >
      github.ref == 'refs/heads/master' && github.event_name == 'push' &&
      !endsWith(needs.build.outputs.artifact_version, '-SNAPSHOT')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          server-id: ossrh # value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
          # gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
          settings-path: ${{ github.workspace }} # store not in a default location to not overwrite by cache restoring

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # TODO add validation to check whether this tag is already submitted or not?
      - name: Version details
        run: echo "Artifact version to publish - ${{ needs.build.outputs.artifact_version }}"

      - name: Package
        run: mvn -B -V -s $GITHUB_WORKSPACE/settings.xml clean package -DskipTests=true -Dcheckstyle.skip=true

      - name: Create release
        # use sha commit references in order to reduce security issues related to unverified actions and their creators
        uses: xresloader/upload-to-github-release@3ad14478ee4fb9bd65e84c6d496a7d6862892f43
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: target/greeting-service-*.jar;target/greeting-service-*.jar.original
          delete_file: greeting-service-*
          tag_name: v${{ needs.build.outputs.artifact_version }}
          draft: true
          overwrite: true
          verbose: true
