name: learn-github-actions
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Compile
        run: mvn -B clean compile

      - name: Test
        run: mvn -B verify -Dmaven.test.failure.ignore=true

      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          report_paths: '**/*-reports/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_test_failures: true
      #          commit: TODO check whether it's acceptable to use workflow_run

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: greeting-service-artifacts
          path: |
            target/greeting-service-*.jar
            target/greeting-service-*.jar.original
          if-no-files-found: error
